### ISSUE TITLE
How to add Chinese language support

### ISSUE THREAD

**Issue by malimaliao** [art567/bf2keyman#1]
Hello, I don’t understand pascal, but I want to add Chinese language support, what should I do?

**Comment by art567** [comment]
You need to edit [app_main.res](/art567/bf2keyman/blob/master/src/app_main.res) by using any Resource Editor app - Visual Studio for example, to insert new string table entries with unique string IDs.

Each ID of the stringtable entry must be calculated by following formula:
StringID := ((LocaleLangID - 1) * 16) + StringIndex

String ID list and it's meanings starts from [Line #201 in main.pas](/art567/bf2keyman/blob/master/src/main.pas#L201)

To find needed Locale ID, please look at [Windows Locale Codes](https://docs.microsoft.com/en-us/openspecs/office_standards/ms-oe376/6c085406-a698-4e12-9d4d-c3b0ee3dbc4a)

Once you have updated [app_main.res](/art567/bf2keyman/blob/master/src/app_main.res), you could replace it's resources in final EXE or build binaries from scratch via [Build.bat batch script](/art567/bf2keyman/blob/master/src/Build.bat).

**Comment by art567** [comment]
Chinese locales can be used from list I've mentioned above:

1028 | zh-TW | Chinese - Taiwan
2052 | zh-CN | Chinese - People's Republic of China
3076 | zh-HK | Chinese - Hong Kong SAR
4100 | zh-SG | Chinese - Singapore
5124 | zh-MO | Chinese - Macao SAR

**Comment by art567** [comment]
Chinese locales can be used from list I've mentioned above:

1028 | zh-TW | Chinese - Taiwan --- StringID starting from 16432
2052 | zh-CN | Chinese - People's Republic of China --- StringID starting from 32816
3076 | zh-HK | Chinese - Hong Kong SAR --- StringID starting from 49200
4100 | zh-SG | Chinese - Singapore --- StringID starting from 65584
5124 | zh-MO | Chinese - Macao SAR --- StringID starting from 81968
---
Some locales defined here probably dont work due to upper Word limit (65535)
App could be redesigned to use every locale listed here
---

The second problem is that chinese uses special extended charsets, that could be available only via Unicode (UTF-16) or WideChar-based charset. All of the mentioned problems could be resolved if it's needed.

**Comment by art567** [comment]
Chinese locales can be used from list I've mentioned above:

1028 | zh-TW | Chinese - Taiwan --- StringID starting from 16432
2052 | zh-CN | Chinese - People's Republic of China --- StringID starting from 32816
3076 | zh-HK | Chinese - Hong Kong SAR --- StringID starting from 49200
4100 | zh-SG | Chinese - Singapore --- StringID starting from 65584
5124 | zh-MO | Chinese - Macao SAR --- StringID starting from 81968

---

Some locales defined here probably dont work due to upper Word limit (65535)
BF2KeyMan App could be easily redesigned to use every locale listed here.

---

The second problem is that chinese uses special extended charsets, that could be available only 
via Unicode (UTF-16) or WideChar-based charset. All of the mentioned problems could be resolved if it's needed.

**Comment by malimaliao** [comment]
> You need to edit [app_main.res](/art567/bf2keyman/blob/master/src/app_main.res) by using any Resource Editor app - Visual Studio for example, to insert new string table entries with unique string IDs.
> 
> Each ID of the stringtable entry must be calculated by following formula:
> StringID := ((LocaleLangID - 1) * 16) + StringIndex
> 
> String ID list and it's meanings starts from [Line #201 in main.pas](/art567/bf2keyman/blob/master/src/main.pas#L201)
> 
> To find needed Locale ID, please look at [Windows Locale Codes](https://docs.microsoft.com/en-us/openspecs/office_standards/ms-oe376/6c085406-a698-4e12-9d4d-c3b0ee3dbc4a)
> 
> Once you have updated [app_main.res](/art567/bf2keyman/blob/master/src/app_main.res), you could replace it's resources in final EXE or build binaries from scratch via [Build.bat batch script](/art567/bf2keyman/blob/master/src/Build.bat).

Thank you!
Do you have any downloads recommended by [Resource Editor app], I downloaded a lot from the Internet and couldn't open the .res file.

**Comment by malimaliao** [comment]
Thank you, i do.


`// 此程序模块，根据传入的语言ID，app_main.res读取对应语言字符
// 该资源文件是由原作者打包，仅包含英语和俄罗斯语
procedure LocalizationFromResource(ID: Cardinal);
begin
  if (FindResource(hInstance, Pointer(ID), RT_STRING) <> 0) then
  begin
    // 当传入的语言ID在资源ID中存在，则进行映射
    L_SET('app.name',      GetResStr(ID, 0));
    L_SET('app.title',     GetResStr(ID, 1));
    L_SET('app.ver',       GetResStr(ID, 2));
    L_SET('btn.apply',     GetResStr(ID, 3));
    L_SET('btn.rand',      GetResStr(ID, 4));
    L_SET('btn.close',     GetResStr(ID, 5));
    L_SET('txt.title',     GetResStr(ID, 6));
    L_SET('txt.desc',      GetResStr(ID, 7));
    L_SET('txt.bf2key',    GetResStr(ID, 8));
    L_SET('txt.bf2sfkey',  GetResStr(ID, 9));
    L_SET('txt.bf2unk',    GetResStr(ID, 10));
    L_SET('txt.bf2act',    GetResStr(ID, 11));
    L_SET('txt.bf2new',    GetResStr(ID, 12));
    L_SET('txt.bf2inv',    GetResStr(ID, 13));
    L_SET('txt.bf2nope',   GetResStr(ID, 14));
  end;
end;

// 此处为添加的固定的中文简体语言
procedure load_lang_chinese();
begin
  // 中文
  L_SET('app.name',      '战地2密钥侠');
  L_SET('app.title',     '战地2密钥侠2');
  L_SET('app.ver',       'v1.0');
  L_SET('btn.apply',     '保存');
  L_SET('btn.rand',      '生成');
  L_SET('btn.close',     '退出');
  L_SET('txt.title',     '战地2密钥侠 bf2keyman');
  L_SET('txt.desc',      '作者：Tema567，汉化：NanFei' + #13 + #13 + '1，首先点击生成按钮会随机生成CD-KEY' + #13 + '2，然后请点击保存按钮，即可退出软件' + #13 + #13 + '* win7和更高版本请选择以管理员身份运行，否则可能激活无效。');
  L_SET('txt.bf2key',    '如果您有战地2密钥，也可以手动填入');
  L_SET('txt.bf2sfkey',  '如果您有战地2:特种部队密钥，也可以手动填入');
  L_SET('txt.bf2unk',    '激活状态：未知');
  L_SET('txt.bf2act',    '激活状态：已激活');
  L_SET('txt.bf2new',    '已生成KEY，请点击保存');
  L_SET('txt.bf2inv',    '密钥无效');
  L_SET('txt.bf2nope',   '尚未激活');
end;

// 此处为添加的固定的中文繁体语言
procedure load_lang_chinese_ft();
begin
  // 中文
  L_SET('app.name',      '戰地2密鑰俠');
  L_SET('app.title',     '戰地2密鑰俠');
  L_SET('app.ver',       'v1.0');
  L_SET('btn.apply',     '保存');
  L_SET('btn.rand',      '生成');
  L_SET('btn.close',     '退出');
  L_SET('txt.title',     '戰地2密鑰俠 bf2keyman');
  L_SET('txt.desc',      '作者：Tema567，中文：NanFei' + #13 + #13 + '1，首先點擊生成按鈕生成CD-KEY' + #13 + '2，然後再點擊保存按鈕，之後可退出程式' + #13 + #13 + '* win7和更高版本請選擇以管理員身份運行，否則可能激活無效');
  L_SET('txt.bf2key',    '如果有戰地2密鑰，可填入');
  L_SET('txt.bf2sfkey',  '如果有戰地2特種部隊密鑰，可填入');
  L_SET('txt.bf2unk',    '激活狀態：未知');
  L_SET('txt.bf2act',    '激活狀態：已經激活');
  L_SET('txt.bf2new',    '已生成KEY，請點擊保存');
  L_SET('txt.bf2inv',    '密鑰無效');
  L_SET('txt.bf2nope',   '尚未激活');
end;

procedure InitLocalization;
const
  ID = 1033; // 1033对应的语言是en_US，属于默认语言
begin
  // 默认语言，从资源映射文件中读取ID1033语言的字符映射
  L_SET('app.name',      GetResStr(ID, 0));
  L_SET('app.title',     GetResStr(ID, 1));
  L_SET('app.ver',       GetResStr(ID, 2));
  L_SET('btn.apply',     GetResStr(ID, 3));
  L_SET('btn.rand',      GetResStr(ID, 4));
  L_SET('btn.close',     GetResStr(ID, 5));
  L_SET('txt.title',     GetResStr(ID, 6));
  L_SET('txt.desc',      GetResStr(ID, 7));
  L_SET('txt.bf2key',    GetResStr(ID, 8));
  L_SET('txt.bf2sfkey',  GetResStr(ID, 9));
  L_SET('txt.bf2unk',    GetResStr(ID, 10));
  L_SET('txt.bf2act',    GetResStr(ID, 11));
  L_SET('txt.bf2new',    GetResStr(ID, 12));
  L_SET('txt.bf2inv',    GetResStr(ID, 13));
  L_SET('txt.bf2nope',   GetResStr(ID, 14));
  // Get Localized strings from resources
  // 获取系统本地语言ID，并根据ID从app_main.res读取对应语言字符
  if GetLanguageID = 2052 then
  begin
    load_lang_chinese(); // 语言ID为2052，强制使用中文
  end
  else if (GetLanguageID = 3076) or (GetLanguageID = 5124) or (GetLanguageID = 1028) then
    begin
      load_lang_chinese_ft(); //强制使用中文繁体
    end
  else
  begin
      LocalizationFromResource( GetLanguageID ); // 其他语言ID尝试使用字符映射
  end;

end;`

**Comment by malimaliao** [comment]
Большое спасибо .
Thank you very much,
I do somthing, it's work.

// add new chinese1
// 此处为添加的固定的中文简体语言
procedure load_lang_chinese();
begin
// 中文
L_SET('app.name', '战地2密钥侠');
L_SET('app.title', '战地2密钥侠2');
L_SET('app.ver', 'v1.0');
L_SET('btn.apply', '保存');
L_SET('btn.rand', '生成');
L_SET('btn.close', '退出');
L_SET('txt.title', '战地2密钥侠 bf2keyman');
L_SET('txt.desc', '作者：Tema567，汉化：dada' + #13 + #13 + '1，首先点击生成按钮会随机生成CD-KEY' + #13 + '2，然后请点击保存按钮，即可退出软件' + #13 + #13 + '* win7和更高版本请选择以管理员身份运行，否则可能激活无效。');
L_SET('txt.bf2key', '如果您有战地2密钥，也可以手动填入');
L_SET('txt.bf2sfkey', '如果您有战地2:特种部队密钥，也可以手动填入');
L_SET('txt.bf2unk', '激活状态：未知');
L_SET('txt.bf2act', '激活状态：已激活');
L_SET('txt.bf2new', '已生成KEY，请点击保存');
L_SET('txt.bf2inv', '密钥无效');
L_SET('txt.bf2nope', '尚未激活');
end;

// add new chinese2
// 此处为添加的固定的中文繁体语言
procedure load_lang_chinese_ft();
begin
// 中文
L_SET('app.name', '戰地2密鑰俠');
L_SET('app.title', '戰地2密鑰俠');
L_SET('app.ver', 'v1.0');
L_SET('btn.apply', '保存');
L_SET('btn.rand', '生成');
L_SET('btn.close', '退出');
L_SET('txt.title', '戰地2密鑰俠 bf2keyman');
L_SET('txt.desc', '作者：Tema567，中文：dada' + #13 + #13 + '1，首先點擊生成按鈕生成CD-KEY' + #13 + '2，然後再點擊保存按鈕，之後可退出程式' + #13 + #13 + '* win7和更高版本請選擇以管理員身份運行，否則可能激活無效');
L_SET('txt.bf2key', '如果有戰地2密鑰，可填入');
L_SET('txt.bf2sfkey', '如果有戰地2特種部隊密鑰，可填入');
L_SET('txt.bf2unk', '激活狀態：未知');
L_SET('txt.bf2act', '激活狀態：已經激活');
L_SET('txt.bf2new', '已生成KEY，請點擊保存');
L_SET('txt.bf2inv', '密鑰無效');
L_SET('txt.bf2nope', '尚未激活');
end;

procedure InitLocalization;
const
ID = 1033; // 1033对应的语言是en_US，属于默认语言
begin
// 默认语言，从资源映射文件中读取ID1033语言的字符映射
L_SET('app.name', GetResStr(ID, 0));
L_SET('app.title', GetResStr(ID, 1));
L_SET('app.ver', GetResStr(ID, 2));
L_SET('btn.apply', GetResStr(ID, 3));
L_SET('btn.rand', GetResStr(ID, 4));
L_SET('btn.close', GetResStr(ID, 5));
L_SET('txt.title', GetResStr(ID, 6));
L_SET('txt.desc', GetResStr(ID, 7));
L_SET('txt.bf2key', GetResStr(ID, 8));
L_SET('txt.bf2sfkey', GetResStr(ID, 9));
L_SET('txt.bf2unk', GetResStr(ID, 10));
L_SET('txt.bf2act', GetResStr(ID, 11));
L_SET('txt.bf2new', GetResStr(ID, 12));
L_SET('txt.bf2inv', GetResStr(ID, 13));
L_SET('txt.bf2nope', GetResStr(ID, 14));
// Get Localized strings from resources
// 获取系统本地语言ID，并根据ID从app_main.res读取对应语言字符
if GetLanguageID = 2052 then
begin
load_lang_chinese(); // 语言ID为2052，强制使用中文
end
else if (GetLanguageID = 3076) or (GetLanguageID = 5124) or (GetLanguageID = 1028) then
begin
load_lang_chinese_ft(); //强制使用中文繁体
end
else
begin
LocalizationFromResource( GetLanguageID ); // 其他语言ID尝试使用字符映射
end;

end;
